/*
 * @Author: yoyo
 * @Date: 2025-12-12 17:31:13
 * @LastEditors: yoyo
 * @LastEditTime: 2026-01-30 17:25:09
 * @FilePath: \next-react\src\app\layout.tsx
 * @Description:
 */
import type { Metadata } from "next";
import { ZCOOL_KuaiLe } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../providers/ThemeProvider";
import Theme from "../components/Theme";
// Bitcount ZCOOL_KuaiLe
const geistSans = ZCOOL_KuaiLe({
 variable: "--font-geist-sans",
 subsets: ["latin"],
 weight: "400",
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en" suppressHydrationWarning>
   <body className={`${geistSans.variable} antialiased`}>
    <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
     <main className="size-full">
      {/* <Navbar /> */}
      {children}
     </main>

     <Theme />
    </ThemeProvider>
   </body>
  </html>
 );
}
